package uk.co.mhl.timezonetracker.core.designsystem.theme

import androidx.compose.ui.graphics.Color

/**
 * Light colors.
 */
val primaryLight = Color(0xFF203467)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF596BA2)
val onPrimaryContainerLight = Color(0xFFFFFFFF)
val secondaryLight = Color(0xFF303648)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFF676C81)
val onSecondaryContainerLight = Color(0xFFFFFFFF)
val tertiaryLight = Color(0xFF003E31)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF287A64)
val onTertiaryContainerLight = Color(0xFFFFFFFF)
val errorLight = Color(0xFF740006)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFCF2C27)
val onErrorContainerLight = Color(0xFFFFFFFF)
val backgroundLight = Color(0xFFFAF8FF)
val onBackgroundLight = Color(0xFF1A1B21)
val surfaceLight = Color(0xFFFAF8FF)
val onSurfaceLight = Color(0xFF101116)
val surfaceVariantLight = Color(0xFFE2E2EC)
val onSurfaceVariantLight = Color(0xFF34363E)
val outlineLight = Color(0xFF50525B)
val outlineVariantLight = Color(0xFF6B6C75)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2F3036)
val inverseOnSurfaceLight = Color(0xFFF1F0F7)
val inversePrimaryLight = Color(0xFFB3C5FF)
val surfaceDimLight = Color(0xFFC6C6CD)
val surfaceBrightLight = Color(0xFFFAF8FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF4F3FA)
val surfaceContainerLight = Color(0xFFE8E7EF)
val surfaceContainerHighLight = Color(0xFFDDDCE3)
val surfaceContainerHighestLight = Color(0xFFD2D1D8)

/**
 * Dark colors.
 */
val primaryDark = Color(0xFFD2DBFF)
val onPrimaryDark = Color(0xFF0C2255)
val primaryContainerDark = Color(0xFF7D8FC8)
val onPrimaryContainerDark = Color(0xFF000000)
val secondaryDark = Color(0xFFD7DBF3)
val onSecondaryDark = Color(0xFF202536)
val secondaryContainerDark = Color(0xFF8B90A5)
val onSecondaryContainerDark = Color(0xFF000000)
val tertiaryDark = Color(0xFF9DECD1)
val onTertiaryDark = Color(0xFF002C21)
val tertiaryContainerDark = Color(0xFF519F87)
val onTertiaryContainerDark = Color(0xFF000000)
val errorDark = Color(0xFFFFD2CC)
val onErrorDark = Color(0xFF540003)
val errorContainerDark = Color(0xFFFF5449)
val onErrorContainerDark = Color(0xFF000000)
val backgroundDark = Color(0xFF121318)
val onBackgroundDark = Color(0xFFE3E2E9)
val surfaceDark = Color(0xFF121318)
val onSurfaceDark = Color(0xFFFFFFFF)
val surfaceVariantDark = Color(0xFF45464F)
val onSurfaceVariantDark = Color(0xFFDBDBE6)
val outlineDark = Color(0xFFB1B1BB)
val outlineVariantDark = Color(0xFF8F9099)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE3E2E9)
val inverseOnSurfaceDark = Color(0xFF292A2F)
val inversePrimaryDark = Color(0xFF33467A)
val surfaceDimDark = Color(0xFF121318)
val surfaceBrightDark = Color(0xFF43444A)
val surfaceContainerLowestDark = Color(0xFF06070C)
val surfaceContainerLowDark = Color(0xFF1C1D23)
val surfaceContainerDark = Color(0xFF26282D)
val surfaceContainerHighDark = Color(0xFF313238)
val surfaceContainerHighestDark = Color(0xFF3C3D43)